// <auto-generated />
namespace EscutaSom.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Criacao_Modelo_Usuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criacao_Modelo_Usuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201901241823250_Criacao_Modelo_Usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
