// <auto-generated />
namespace EscutaSom.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddField_Media_in_Faixa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddField_Media_in_Faixa));
        
        string IMigrationMetadata.Id
        {
            get { return "201901291314436_Add-Field_Media_in_Faixa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
